name = "ai-interview"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[vars]
SECRET_KEY = "tUzr6Mh4QU6hxl2pUQtTrnZgMN8P/X//SkqwRVTQr9IrVmxO7WDd4naPQmmWIyiD"
AI_BASE_URL = "https://api.deepseek.com"
AI_API_KEY = "sk-81e157e3735240d7ae1cc8a4cfa16dab"

[[d1_databases]]
binding = "DB"
database_name = "ai-interview-db"
database_id = "3f82993e-210d-4b0b-9d83-4ed4be69724f"

# [ai]
# binding = "AI"
# NOTE: 本地 `wrangler pages dev` 需注释掉；生产部署 `wrangler pages deploy` 时取消注释
